# generated by datamodel-codegen:
#   filename:  openapi-v1.json

from __future__ import annotations

from enum import StrEnum
from typing import Any
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class ChatMode(StrEnum):
    """
    Built-in chat modes (spec §8.2). ``custom`` is the escape hatch for
    tenant-defined modes; the human-readable label lives in
    ``Conversation.custom_mode_name``.
    """

    planning = 'planning'
    discussion = 'discussion'
    execution = 'execution'
    custom = 'custom'


class ConversationResponse(BaseModel):
    created_at: AwareDatetime = Field(..., title='Created At')
    created_by: UUID | None = Field(..., title='Created By')
    current_mode: str = Field(..., title='Current Mode')
    custom_mode_name: str | None = Field(..., title='Custom Mode Name')
    id: UUID = Field(..., title='Id')
    project_id: UUID = Field(..., title='Project Id')
    related_plan_id: UUID | None = Field(..., title='Related Plan Id')
    tenant_id: UUID = Field(..., title='Tenant Id')
    title: str | None = Field(..., title='Title')
    updated_at: AwareDatetime = Field(..., title='Updated At')


class KbCategorySummary(BaseModel):
    """
    Slim embed para `KnowledgeBaseResponse.category` — evita un
    fetch extra del frontend cuando lista KBs.
    """

    color: str | None = Field(..., title='Color')
    id: UUID = Field(..., title='Id')
    is_builtin: bool = Field(..., title='Is Builtin')
    name: str = Field(..., title='Name')
    slug: str = Field(..., title='Slug')


class KnowledgeBaseResponse(BaseModel):
    category: KbCategorySummary | None = None
    created_at: AwareDatetime = Field(..., title='Created At')
    created_by: UUID | None = Field(..., title='Created By')
    description: str | None = Field(..., title='Description')
    embedding_model_id: str = Field(..., title='Embedding Model Id')
    id: UUID = Field(..., title='Id')
    is_builtin: bool | None = Field(False, title='Is Builtin')
    name: str = Field(..., title='Name')
    tenant_id: UUID = Field(..., title='Tenant Id')
    updated_at: AwareDatetime = Field(..., title='Updated At')


class PlanResponse(BaseModel):
    approved_at: AwareDatetime | None = Field(..., title='Approved At')
    approved_by: UUID | None = Field(..., title='Approved By')
    conversation_id: UUID | None = Field(..., title='Conversation Id')
    created_at: AwareDatetime = Field(..., title='Created At')
    created_by: UUID | None = Field(..., title='Created By')
    description: str | None = Field(..., title='Description')
    first_approved_at: AwareDatetime | None = Field(..., title='First Approved At')
    first_approved_by: UUID | None = Field(..., title='First Approved By')
    id: UUID = Field(..., title='Id')
    project_id: UUID = Field(..., title='Project Id')
    specification: dict[str, Any] = Field(..., title='Specification')
    status: str = Field(..., title='Status')
    tenant_id: UUID = Field(..., title='Tenant Id')
    title: str = Field(..., title='Title')
    updated_at: AwareDatetime = Field(..., title='Updated At')


class PlanStatus(StrEnum):
    """
    Full lifecycle of a plan (Plan 03 task_03_16 / task_03_25).

    Transitions are enforced in `api_server.chat.plan_state_machine`.
    A freshly POSTed plan from the chat lands in ``draft``; the human
    moves it to ``pending_approval`` to start the review.

    When the AI cost estimate exceeds the platform-configured double-
    signature threshold (task_03_25), the first approval moves the
    plan to ``pending_second_approval``; a **different** signer must
    confirm to reach ``approved``. Below the threshold a single firma
    is enough (``pending_approval -> approved``).

    Executions of approved plans flip them through ``in_progress``,
    ``blocked``, then ``pending_human_validation`` and finally
    ``completed``.
    """

    pending_approval = 'pending_approval'
    pending_second_approval = 'pending_second_approval'
    draft = 'draft'
    approved = 'approved'
    in_progress = 'in_progress'
    blocked = 'blocked'
    pending_human_validation = 'pending_human_validation'
    completed = 'completed'
    cancelled = 'cancelled'
    rejected = 'rejected'
    archived = 'archived'


class BudgetAmount(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: str = Field(..., pattern='^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$', title='Budget Amount')


class ProjectResponse(BaseModel):
    budget_amount: BudgetAmount | None = Field(..., title='Budget Amount')
    budget_currency: str | None = Field(..., title='Budget Currency')
    budget_period: str | None = Field(..., title='Budget Period')
    budget_period_length_days: int | None = Field(..., title='Budget Period Length Days')
    budget_period_start_day: int | None = Field(..., title='Budget Period Start Day')
    created_at: AwareDatetime = Field(..., title='Created At')
    deleted_at: AwareDatetime | None = Field(..., title='Deleted At')
    description: str | None = Field(..., title='Description')
    human_approval_policy: dict[str, Any] | None = Field(..., title='Human Approval Policy')
    id: UUID = Field(..., title='Id')
    is_template: bool = Field(..., title='Is Template')
    mcp_servers: list[dict[str, Any]] = Field(..., title='Mcp Servers')
    name: str = Field(..., title='Name')
    paused_by_budget: bool = Field(..., title='Paused By Budget')
    rag_knowledge_bases: list[dict[str, Any]] = Field(..., title='Rag Knowledge Bases')
    repository_config: dict[str, Any] | None = Field(..., title='Repository Config')
    secrets_vault_id: UUID | None = Field(..., title='Secrets Vault Id')
    status: str = Field(..., title='Status')
    team_id: UUID | None = Field(..., title='Team Id')
    tenant_id: UUID = Field(..., title='Tenant Id')
    updated_at: AwareDatetime = Field(..., title='Updated At')
    worker_config: dict[str, Any] = Field(..., title='Worker Config')


class ProjectStatus(StrEnum):
    active = 'active'
    paused = 'paused'
    archived = 'archived'


class TaskPriority(StrEnum):
    low = 'low'
    medium = 'medium'
    high = 'high'
    critical = 'critical'


class TaskResponse(BaseModel):
    acceptance_criteria: list[Any] = Field(..., title='Acceptance Criteria')
    assigned_agent_id: UUID | None = Field(..., title='Assigned Agent Id')
    completed_at: AwareDatetime | None = Field(..., title='Completed At')
    created_at: AwareDatetime = Field(..., title='Created At')
    depends_on: list[UUID] = Field(..., title='Depends On')
    description: str | None = Field(..., title='Description')
    estimated_complexity: str | None = Field(..., title='Estimated Complexity')
    id: UUID = Field(..., title='Id')
    inputs: dict[str, Any] = Field(..., title='Inputs')
    max_retries: int = Field(..., title='Max Retries')
    plan_id: UUID | None = Field(..., title='Plan Id')
    priority: str = Field(..., title='Priority')
    project_id: UUID = Field(..., title='Project Id')
    retry_count: int = Field(..., title='Retry Count')
    reviewer_agent_id: UUID | None = Field(..., title='Reviewer Agent Id')
    started_at: AwareDatetime | None = Field(..., title='Started At')
    status: str = Field(..., title='Status')
    tenant_id: UUID = Field(..., title='Tenant Id')
    title: str = Field(..., title='Title')
    updated_at: AwareDatetime = Field(..., title='Updated At')


class TaskStatus(StrEnum):
    backlog = 'backlog'
    ready = 'ready'
    in_progress = 'in_progress'
    awaiting_human_approval = 'awaiting_human_approval'
    in_review = 'in_review'
    blocked = 'blocked'
    done = 'done'
    cancelled = 'cancelled'


class Title(RootModel[str]):
    root: str = Field(..., max_length=255, title='Title')


class V1ConversationCreateRequest(BaseModel):
    """
    Minimal public body to start a conversation in a project.
    """

    current_mode: ChatMode | None = 'planning'
    title: Title | None = Field(None, title='Title')


class EmbeddingModelId(RootModel[str]):
    root: str = Field(..., max_length=120, title='Embedding Model Id')


class V1KnowledgeBaseCreateRequest(BaseModel):
    """
    Minimal public body to create a knowledge base.
    """

    description: str | None = Field(None, title='Description')
    embedding_model_id: EmbeddingModelId | None = Field(None, title='Embedding Model Id')
    name: str = Field(..., max_length=120, min_length=1, title='Name')


class V1PlanCreateRequest(BaseModel):
    """
    Minimal public body to create a (draft) plan in a project.

    The specification is left empty; the public API creates the plan
    shell — filling the canonical-template spec stays a planning-chat /
    interactive concern.
    """

    description: str | None = Field(None, title='Description')
    status: PlanStatus | None = 'draft'
    title: str = Field(..., max_length=255, min_length=1, title='Title')


class V1ProjectCreateRequest(BaseModel):
    """
    Minimal public body to create a project.
    """

    description: str | None = Field(None, title='Description')
    name: str = Field(..., max_length=255, min_length=1, title='Name')
    status: ProjectStatus | None = 'active'


class V1TaskCreateRequest(BaseModel):
    """
    Minimal public body to create a task in a project.
    """

    description: str | None = Field(None, title='Description')
    priority: TaskPriority | None = 'medium'
    status: TaskStatus | None = 'backlog'
    title: str = Field(..., max_length=200, min_length=1, title='Title')


class ValidationError(BaseModel):
    ctx: dict[str, Any] | None = Field(None, title='Context')
    input: Any | None = Field(None, title='Input')
    loc: list[str | int] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(None, title='Detail')
