"""Deterministic post-plan documentation generation (task_07_06).

At plan close the Technical Writer agent (task_07_05) must materialise the
plan's documentation deliverables under ``/docs``. The *wording* may come
from the agent, but the **file structure is generated by code** so the
structural (task_07_02), markdownlint (task_07_03) and language (task_07_04)
gates of Fase A always pass and the output is reproducible.

This module owns that deterministic core: :func:`generate_plan_docs`. Given
a docs root and a closed plan's metadata it

  * writes ``docs/07-changelog/<plan_id>.md`` via
    :func:`~api_server.tech_writer.changelog.render_changelog` (task_07_07),
    **only if the file is missing** — a human-edited changelog is never
    clobbered;
  * for each declared decision, allocates the next sequential ADR number
    with :func:`~api_server.tech_writer.adr.next_adr_number` (task_07_08)
    and writes ``docs/05-architecture-decisions/NNNN-<slug>.md`` via
    :func:`~api_server.tech_writer.adr.render_adr` — again skip-if-exists,
    so a re-run never duplicates or overwrites;
  * returns a :class:`GenerationManifest` describing every file the call
    wrote, skipped or would-have-updated.

**Idempotency contract.** Re-running ``generate_plan_docs`` on a tree it
already generated produces *no* new files and mutates *nothing*: the
changelog already exists (skipped) and each decision's ADR is matched to
its existing file by slug (skipped) rather than allocated a fresh number.
That makes the workflow safe to invoke on every plan-close attempt.

**Reference updates** (``docs/04-reference/``) are intentionally a *no-op*
here: deriving them deterministically needs a structured API/schema source
this plan does not provide. The manifest records this as an explicit
``reference_note`` rather than fabricating reference pages. See the task
report / ``REFERENCE_UPDATE_NOTE``.

The sole I/O is reading the ADR directory listing (to allocate numbers and
detect existing ADRs) and writing the new Markdown files. No clock, no
network, no DB — ``session_or_repo`` in the task brief reduces, for the
deterministic core, to the docs-root path the worktree exposes.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

import structlog

from api_server.docs_structure.constants import CANONICAL_DOC_FOLDER_NAMES, DOCS_DIRNAME
from api_server.tech_writer.adr import (
    AdrMeta,
    adr_filename_stem,
    next_adr_number,
    render_adr,
)
from api_server.tech_writer.changelog import (
    DEFAULT_DOCS_LANGUAGE,
    PlanMeta,
    render_changelog,
)

_log = structlog.get_logger("api_server.tech_writer.generation")

# --- canonical sub-folders (named, derived from the single source) ----------
# We do NOT re-declare folder names here: they come from the Fase-A constant
# so generation and validation can never disagree (CLAUDE.md principle 8).
CHANGELOG_FOLDER = "07-changelog"
ADR_FOLDER = "05-architecture-decisions"
REFERENCE_FOLDER = "04-reference"

# Defensive parity check at import time: the folders we write into must be
# part of the canonical set. A drift here is a programming error, not a
# runtime condition, so failing fast is correct.
assert CHANGELOG_FOLDER in CANONICAL_DOC_FOLDER_NAMES
assert ADR_FOLDER in CANONICAL_DOC_FOLDER_NAMES
assert REFERENCE_FOLDER in CANONICAL_DOC_FOLDER_NAMES

#: Markdown extension for generated docs.
MARKDOWN_SUFFIX = ".md"

#: Why ``docs/04-reference/`` is not touched by the deterministic core. The
#: manifest surfaces this so a caller (or a human reviewer) knows reference
#: updates were *deliberately* skipped, not forgotten.
REFERENCE_UPDATE_NOTE = (
    "Reference updates (docs/04-reference/) are a deliberate no-op: this "
    "deterministic generator has no structured API/schema source to derive "
    "them from. The Technical Writer agent edits reference pages manually "
    "when a plan touches APIs or schemas."
)


@dataclass(frozen=True)
class DecisionSpec:
    """One architecture decision a plan declared, to be rendered as an ADR.

    Unlike :class:`~api_server.tech_writer.changelog.ChangelogDecision`
    (which is just the one-line bullet for the changelog), this carries the
    full ADR body so :func:`render_adr` can materialise the record. The
    sequential ``number`` is **not** here — :func:`generate_plan_docs`
    allocates it deterministically via :func:`next_adr_number`.

    Attributes:
        slug: Filename slug (no number, no extension), e.g.
            ``"docs-generation-post-plan"``. Doubles as the identity used
            to detect an already-generated ADR on a re-run (skip-if-exists
            matches on ``*-<slug>.md``).
        title: Decision title (H1 + frontmatter).
        context: Free text for ``## Contexto``.
        decision: Free text for ``## Decisión``.
        consequences: Free text for ``## Consecuencias``.
        alternatives: Optional ``## Alternativas consideradas`` bullets.
        references: Optional ``## Referencias`` bullets.
        status: ADR lifecycle status (defaults to the ADR module's default).
        date: ISO date string for the frontmatter, or ``None``.
        authors: Frontmatter authors; defaults to the ADR module's default.
    """

    slug: str
    title: str
    context: str
    decision: str
    consequences: str
    alternatives: tuple[str, ...] = field(default_factory=tuple)
    references: tuple[str, ...] = field(default_factory=tuple)
    status: str | None = None
    date: str | None = None
    authors: tuple[str, ...] | None = None


@dataclass(frozen=True)
class WrittenFile:
    """One file the generator wrote (created on disk for the first time).

    ``path`` is the absolute POSIX path. ``kind`` is ``"changelog"`` or
    ``"adr"``. For an ADR, ``adr_number`` records the allocated sequential
    number so the caller can cross-link it (e.g. in the changelog).
    """

    path: str
    kind: str
    adr_number: int | None = None


@dataclass(frozen=True)
class SkippedFile:
    """One file the generator left untouched because it already existed.

    Skipping is how idempotency + "never clobber a human edit" are honoured:
    a second run reports the same files as skipped rather than rewriting
    them. ``reason`` is a short machine-stable token (``"exists"``).
    """

    path: str
    kind: str
    reason: str = "exists"
    adr_number: int | None = None


@dataclass(frozen=True)
class GenerationManifest:
    """What :func:`generate_plan_docs` did, for the caller / a re-run check.

    Attributes:
        written: Files newly created by this call, in generation order
            (changelog first, then ADRs).
        skipped: Files that already existed and were left untouched.
        reference_note: The :data:`REFERENCE_UPDATE_NOTE` (always present),
            documenting why ``docs/04-reference/`` was not modified.
    """

    written: tuple[WrittenFile, ...] = field(default_factory=tuple)
    skipped: tuple[SkippedFile, ...] = field(default_factory=tuple)
    reference_note: str = REFERENCE_UPDATE_NOTE

    @property
    def changed(self) -> bool:
        """``True`` iff this call created at least one file.

        A fully idempotent re-run yields ``changed is False`` — the most
        useful single-bit signal for "was anything generated?".
        """
        return len(self.written) > 0


def _docs_root(docs_root: Path) -> Path:
    """Resolve the docs root, tolerating either a repo root or a docs dir.

    The caller may hand us the repo working tree (``…/repo``) or the docs
    directory itself (``…/repo/docs``). We detect the latter by its name so
    a worker that already holds the docs path does not double-nest into
    ``docs/docs``.
    """
    resolved = docs_root.resolve()
    if resolved.name == DOCS_DIRNAME:
        return resolved
    return resolved / DOCS_DIRNAME


def _find_existing_adr(adr_dir: Path, slug: str) -> Path | None:
    """Return the existing ADR file whose name ends in ``-<slug>.md``, if any.

    ADRs are identified on a re-run by their slug, not their number: the
    number was allocated on the first run and we must not re-allocate a new
    one. The match is on the canonical ``NNNN-<slug>.md`` tail.
    """
    if not adr_dir.is_dir():
        return None
    suffix = f"-{slug}{MARKDOWN_SUFFIX}"
    for entry in sorted(adr_dir.iterdir()):
        if entry.is_file() and entry.name.endswith(suffix):
            return entry
    return None


def generate_plan_docs(
    docs_root: Path,
    plan_meta: PlanMeta,
    decisions: tuple[DecisionSpec, ...] = (),
) -> GenerationManifest:
    """Generate a closed plan's documentation deliverables, idempotently.

    Writes the per-plan changelog and one ADR per declared decision under
    the canonical ``/docs`` folders, skipping any file that already exists
    so the call never clobbers human edits and is safe to re-run.

    Args:
        docs_root: Either the repo working-tree root (we then nest into
            ``docs/``) or the ``docs/`` directory itself. The canonical
            sub-folders are created if missing.
        plan_meta: The closed plan's metadata; rendered into the changelog
            via :func:`render_changelog`. Its ``docs_language`` also drives
            the ADR language unless a :class:`DecisionSpec` overrides it.
        decisions: The plan's declared decisions, each materialised as a
            sequentially-numbered ADR via :func:`render_adr`. Empty ⇒ no
            ADRs are written.

    Returns:
        A :class:`GenerationManifest` listing files written + skipped, and
        the (always-present) :data:`REFERENCE_UPDATE_NOTE`.
    """
    root = _docs_root(docs_root)
    changelog_dir = root / CHANGELOG_FOLDER
    adr_dir = root / ADR_FOLDER

    written: list[WrittenFile] = []
    skipped: list[SkippedFile] = []

    # (a) changelog — skip-if-exists so a human-edited entry survives.
    changelog_path = changelog_dir / f"{plan_meta.plan_id}{MARKDOWN_SUFFIX}"
    if changelog_path.exists():
        skipped.append(SkippedFile(path=changelog_path.resolve().as_posix(), kind="changelog"))
    else:
        changelog_dir.mkdir(parents=True, exist_ok=True)
        changelog_path.write_text(render_changelog(plan_meta), encoding="utf-8")
        written.append(WrittenFile(path=changelog_path.resolve().as_posix(), kind="changelog"))

    # (b) one ADR per declared decision, numbered sequentially. We allocate
    # the next number ONCE up front, then bump our own counter per *new*
    # ADR — re-reading the dir between writes would also work but this keeps
    # numbering stable within a single call even before the file lands.
    if decisions:
        adr_dir.mkdir(parents=True, exist_ok=True)
        next_number = next_adr_number(adr_dir)
        for spec in decisions:
            existing = _find_existing_adr(adr_dir, spec.slug)
            if existing is not None:
                skipped.append(SkippedFile(path=existing.resolve().as_posix(), kind="adr"))
                continue
            adr_meta = _build_adr_meta(spec, next_number, plan_meta)
            adr_path = adr_dir / f"{adr_filename_stem(adr_meta)}{MARKDOWN_SUFFIX}"
            adr_path.write_text(render_adr(adr_meta), encoding="utf-8")
            written.append(
                WrittenFile(
                    path=adr_path.resolve().as_posix(),
                    kind="adr",
                    adr_number=next_number,
                )
            )
            next_number += 1

    manifest = GenerationManifest(written=tuple(written), skipped=tuple(skipped))
    _log.info(
        "tech_writer.generate_plan_docs",
        plan_id=plan_meta.plan_id,
        written=len(manifest.written),
        skipped=len(manifest.skipped),
        decisions=len(decisions),
    )
    return manifest


def _build_adr_meta(spec: DecisionSpec, number: int, plan_meta: PlanMeta) -> AdrMeta:
    """Build the :class:`AdrMeta` for ``spec`` at the allocated ``number``.

    The ADR inherits the plan's ``docs_language`` and back-references the
    plan id. Per-decision overrides (status / date / authors) win when set,
    otherwise the ADR module's own defaults apply.
    """
    language = plan_meta.docs_language or DEFAULT_DOCS_LANGUAGE
    kwargs: dict[str, object] = {
        "number": number,
        "title": spec.title,
        "slug": spec.slug,
        "context": spec.context,
        "decision": spec.decision,
        "consequences": spec.consequences,
        "alternatives": spec.alternatives,
        "references": spec.references,
        "date": spec.date,
        "plan_referenced": plan_meta.plan_id,
        "docs_language": language,
    }
    if spec.status is not None:
        kwargs["status"] = spec.status
    if spec.authors is not None:
        kwargs["authors"] = spec.authors
    return AdrMeta(**kwargs)  # type: ignore[arg-type]


__all__ = [
    "ADR_FOLDER",
    "CHANGELOG_FOLDER",
    "REFERENCE_FOLDER",
    "REFERENCE_UPDATE_NOTE",
    "DecisionSpec",
    "GenerationManifest",
    "SkippedFile",
    "WrittenFile",
    "generate_plan_docs",
]
