"use client";

/**
 * MermaidDiagram — renders a fenced ```mermaid block to an SVG (Plan 07
 * task_07_12).
 *
 * Mermaid is heavy (~500 KB) and only runs in the browser, so it is loaded
 * lazily with a dynamic `import()` the first time a diagram mounts; the module
 * is then memoised across diagrams. `securityLevel: "strict"` keeps mermaid
 * from emitting clickable scripts / arbitrary HTML, matching the renderer's
 * no-raw-HTML stance. A parse/render failure degrades to the raw diagram
 * source in a code block rather than throwing — a malformed diagram must never
 * blank the whole doc.
 */

import { useEffect, useId, useRef, useState } from "react";

import { Spinner } from "@/components/ui/spinner";
import { useT } from "@/lib/i18n";
import { cn } from "@/lib/utils";

// Mermaid's API surface we touch — typed locally so we don't pull mermaid's
// types into the server graph and never need `any`.
interface MermaidModule {
  initialize: (config: Record<string, unknown>) => void;
  render: (id: string, code: string) => Promise<{ svg: string }>;
}

let mermaidPromise: Promise<MermaidModule> | null = null;

function loadMermaid(): Promise<MermaidModule> {
  if (mermaidPromise === null) {
    mermaidPromise = import("mermaid").then((mod) => {
      const mermaid = (mod.default ?? mod) as unknown as MermaidModule;
      mermaid.initialize({
        startOnLoad: false,
        securityLevel: "strict",
        theme: "neutral",
        fontFamily: "inherit",
      });
      return mermaid;
    });
  }
  return mermaidPromise;
}

export function MermaidDiagram({ code }: { code: string }) {
  const t = useT("docs");
  const reactId = useId();
  // Mermaid ids must be valid CSS selectors; `useId()` contains ':' so strip it.
  const renderId = `mermaid-${reactId.replace(/[^a-zA-Z0-9_-]/g, "")}`;
  const [svg, setSvg] = useState<string | null>(null);
  const [failed, setFailed] = useState(false);
  // Guards against a state update after unmount when the async render resolves.
  const mountedRef = useRef(true);

  useEffect(() => {
    mountedRef.current = true;
    setSvg(null);
    setFailed(false);

    loadMermaid()
      .then((mermaid) => mermaid.render(renderId, code))
      .then(({ svg: rendered }) => {
        if (mountedRef.current) {
          setSvg(rendered);
        }
      })
      .catch(() => {
        if (mountedRef.current) {
          setFailed(true);
        }
      });

    return () => {
      mountedRef.current = false;
    };
  }, [code, renderId]);

  if (failed) {
    // Fall back to the raw source so the author still sees their diagram text.
    return (
      <pre
        className="border-border bg-muted/40 my-4 overflow-x-auto rounded-lg border p-4 text-sm"
        data-testid="docs-mermaid-error"
      >
        <code>{code}</code>
      </pre>
    );
  }

  if (svg === null) {
    return (
      <div
        className="border-border bg-muted/40 text-muted-foreground my-4 flex items-center gap-2 rounded-lg border p-4 text-sm"
        data-testid="docs-mermaid-loading"
      >
        <Spinner className="h-4 w-4" />
        {t("mermaidLoading")}
      </div>
    );
  }

  return (
    <div
      className={cn(
        "border-border bg-card my-4 overflow-x-auto rounded-lg border p-4",
        "flex justify-center [&_svg]:max-w-full",
      )}
      data-testid="docs-mermaid"
      // Mermaid output is generated by mermaid itself in strict mode (no raw
      // user HTML / scripts), not author-supplied markup, so injecting its SVG
      // is safe — this is the one sanctioned use of dangerouslySetInnerHTML.
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}
