"use client";

import { type FieldErrors, type TenantConfig } from "@/lib/config";

import { Field, TextInput } from "./fields";

interface TenantStepProps {
  value: TenantConfig;
  errors: FieldErrors;
  onChange: (partial: Partial<TenantConfig>) => void;
}

/**
 * Step 6 — initial tenant (task_15_03): the first tenant created at install
 * time and its admin user. The admin's first credentials are generated by the
 * install step (15_06) and shown ONCE; here we only capture name + email.
 */
export function TenantStep({ value, errors, onChange }: TenantStepProps) {
  return (
    <section data-testid="step-tenant" className="flex flex-col gap-5">
      <header className="flex flex-col gap-1">
        <h2 className="text-2xl font-semibold tracking-tight">Tenant inicial</h2>
        <p className="text-muted-foreground max-w-prose text-sm">
          Crea el primer tenant y su usuario administrador. La contraseña inicial se generará y se
          mostrará una sola vez al finalizar la instalación.
        </p>
      </header>

      <Field id="tenantName" label="Nombre del tenant" error={errors.tenantName}>
        <TextInput
          id="tenantName"
          value={value.tenantName}
          onChange={(tenantName) => onChange({ tenantName })}
          placeholder="Acme Corp"
          error={Boolean(errors.tenantName)}
        />
      </Field>

      <Field
        id="adminEmail"
        label="Email del administrador"
        error={errors.adminEmail}
        hint="Recibirá el acceso inicial al panel de administración."
      >
        <TextInput
          id="adminEmail"
          value={value.adminEmail}
          onChange={(adminEmail) => onChange({ adminEmail })}
          placeholder="admin@acme.com"
          autoComplete="off"
          error={Boolean(errors.adminEmail)}
        />
      </Field>
    </section>
  );
}
