"""Finalize step 9 — credentials shown ONCE + self-destruct (Plan 15 task_15_06).

Step 9 is the terminal step of the wizard. Once the install pipeline (step 8,
task 15_05) has completed successfully, the operator is shown — **exactly
once** — the credentials the installer generated and the Vault *unseal keys*.
Per the plan's Decisiones Clave there is no recovery: the operator MUST save
them. Right after that one-time reveal the temporary installer **self-destructs**
(the bootstrap compose stops + removes the installer container) so the UI — and
the in-memory copy of the secrets — is gone.

What this module owns
---------------------
* :class:`InstallCredentials` — the one-shot secret payload. It lives ONLY in
  memory, is never written to ``/data`` or any file, and is never logged.
* :class:`FinalizeService` — the state machine for the reveal:

      not-installed ──arm()──▶ armed ──reveal()──▶ revealed (+ self-destruct)

  - ``arm(credentials)`` is called by the install orchestration the moment the
    pipeline reaches its terminal success state. Until then the service is
    *not installed* and ``reveal()`` refuses to do anything.
  - ``reveal()`` returns the payload the FIRST time it is called on an armed
    service, then immediately **invalidates** the in-memory copy and invokes
    the injected self-destruct seam. Every later call gets nothing (it's gone).
  - On an incomplete install ``reveal()`` raises :class:`InstallNotCompleteError`
    and does NOT reveal creds nor self-destruct.

Security
--------
The credentials and unseal keys are held in a :class:`InstallCredentials`
instance whose ``__repr__``/``__str__`` are redacted so they can't leak into a
log line or a traceback. The installer never persists them in plaintext: the
real secrets are written to Vault by Phase B's bootstrap, not here. The reveal
is a single in-memory hand-off to the operator over loopback; after it the copy
is dropped. Self-destruct lives behind the :class:`installer_backend.seams.
InstallerLifecycle` seam (mocked in tests; the real binding signals the
bootstrap compose).
"""

from __future__ import annotations

from dataclasses import dataclass, field

from installer_backend.seams import InstallerLifecycle


class FinalizeError(Exception):
    """Base class for finalize-step errors."""


class InstallNotCompleteError(FinalizeError):
    """Raised when a reveal is attempted before the install completed.

    An incomplete install must NOT reveal credentials nor self-destruct — the
    operator only gets the secrets once provisioning actually succeeded.
    """


class CredentialsAlreadyRevealedError(FinalizeError):
    """Raised on a second reveal attempt — the one-time payload is gone.

    The credentials are shown exactly once (Decisiones Clave: no recovery).
    After the first reveal the in-memory copy is dropped, so a second fetch can
    only be denied.
    """


@dataclass(frozen=True)
class InstallCredentials:
    """The one-shot secret payload shown to the operator exactly once.

    Lives ONLY in memory while the install is armed, and is dropped right after
    the single reveal. NEVER written to disk and NEVER logged — ``__repr__`` and
    ``__str__`` are redacted so an accidental ``log.info(creds)`` or a traceback
    frame cannot leak the values.

    Fields
    ------
    admin_username / admin_password
        The initial tenant's admin login. The password is generated by the
        install (it is never chosen in the wizard) and shown only here.
    vault_root_token
        Vault's initial root token from ``vault operator init``.
    vault_unseal_keys
        The Shamir unseal-key shares from ``vault operator init``. The operator
        must store these securely; without them Vault cannot be unsealed after a
        restart and there is NO recovery.
    """

    admin_username: str
    admin_password: str
    vault_root_token: str
    vault_unseal_keys: tuple[str, ...]

    def __repr__(self) -> str:  # pragma: no cover - trivial, but security-load-bearing
        return "InstallCredentials(<redacted: shown once, never logged>)"

    __str__ = __repr__


@dataclass(frozen=True)
class CredentialField:
    """One labelled credential line for the one-time reveal payload.

    ``secret`` is the value the operator copies. The list of these IS the
    reveal — there is no other surface that carries the secret values.
    """

    key: str
    label_es: str
    label_en: str
    secret: str


@dataclass(frozen=True)
class RevealPayload:
    """The structured one-time reveal returned by :meth:`FinalizeService.reveal`.

    ``credentials`` are the labelled secret lines; ``unseal_keys`` are the Vault
    unseal-key shares (kept separate because they are the highest-value, no-
    recovery secret the operator must store). ``warning_es``/``warning_en`` are
    the "save these now, they are shown only once" notice the UI renders.
    """

    credentials: tuple[CredentialField, ...]
    unseal_keys: tuple[str, ...]
    warning_es: str = (
        "Guarda estas credenciales y las unseal keys de Vault AHORA. "
        "Se muestran una sola vez y no hay forma de recuperarlas."
    )
    warning_en: str = (
        "Save these credentials and Vault unseal keys NOW. "
        "They are shown only once and cannot be recovered."
    )


def build_reveal(credentials: InstallCredentials) -> RevealPayload:
    """Project :class:`InstallCredentials` into the UI-facing reveal payload."""

    fields = (
        CredentialField(
            key="admin_username",
            label_es="Usuario administrador",
            label_en="Admin username",
            secret=credentials.admin_username,
        ),
        CredentialField(
            key="admin_password",
            label_es="Contraseña del administrador",
            label_en="Admin password",
            secret=credentials.admin_password,
        ),
        CredentialField(
            key="vault_root_token",
            label_es="Token root de Vault",
            label_en="Vault root token",
            secret=credentials.vault_root_token,
        ),
    )
    return RevealPayload(credentials=fields, unseal_keys=credentials.vault_unseal_keys)


@dataclass
class FinalizeService:
    """One-time reveal + self-destruct state machine for wizard step 9.

    Construct with an injected :class:`InstallerLifecycle` seam (a recording
    fake in tests; the real binding signals the bootstrap compose in Phase B).
    The service starts *not installed*: until :meth:`arm` is called by the
    orchestration on a successful install, :meth:`reveal` refuses to reveal or
    self-destruct. :meth:`reveal` then hands the payload over exactly once,
    drops the in-memory copy, and triggers self-destruct.
    """

    lifecycle: InstallerLifecycle
    #: The armed credentials, or ``None`` before arming / after the reveal.
    _credentials: InstallCredentials | None = field(default=None, init=False)
    #: True once the install pipeline completed and the service was armed.
    _installed: bool = field(default=False, init=False)
    #: True once the (single) reveal has happened — the payload is gone.
    _revealed: bool = field(default=False, init=False)

    @property
    def installed(self) -> bool:
        """True once a successful install armed this service."""

        return self._installed

    @property
    def revealed(self) -> bool:
        """True once the one-time reveal has been served."""

        return self._revealed

    @property
    def can_reveal(self) -> bool:
        """True iff a reveal would succeed right now (armed and not yet shown)."""

        return self._installed and not self._revealed and self._credentials is not None

    def arm(self, credentials: InstallCredentials) -> None:
        """Arm the reveal after a successful install.

        Called by the orchestration the moment the pipeline reaches terminal
        success. Stores the one-shot credentials in memory and marks the
        service installed. Re-arming after a reveal is refused — the secrets are
        a one-time payload.
        """

        if self._revealed:
            raise CredentialsAlreadyRevealedError(
                "Las credenciales ya se mostraron una vez; no pueden re-armarse."
            )
        self._credentials = credentials
        self._installed = True

    def reveal(self) -> RevealPayload:
        """Reveal the credentials + unseal keys EXACTLY ONCE.

        On the first call against an armed service this returns the reveal
        payload, then immediately invalidates the in-memory copy and asks the
        installer to self-destruct. A second call raises
        :class:`CredentialsAlreadyRevealedError`. If the install never completed it
        raises :class:`InstallNotCompleteError` and does NOT self-destruct.
        """

        # Order matters: a service that was armed-then-revealed has both
        # `_revealed=True` and `_credentials=None`. Check "already revealed"
        # FIRST so a second fetch is denied as Gone (410) rather than being
        # mistaken for an incomplete install (409).
        if self._revealed:
            raise CredentialsAlreadyRevealedError(
                "Las credenciales ya se mostraron una vez y no se pueden recuperar."
            )
        if not self._installed or self._credentials is None:
            # Incomplete install: never reveal, never self-destruct.
            raise InstallNotCompleteError(
                "La instalación no se ha completado; no hay credenciales que mostrar."
            )

        payload = build_reveal(self._credentials)

        # Invalidate the one-shot payload BEFORE self-destruct so the secret is
        # already gone from memory regardless of how the seam behaves.
        self._credentials = None
        self._revealed = True

        # Self-destruct only AFTER a successful reveal (the one-time hand-off
        # happened); behind the injectable seam (mocked in tests).
        self.lifecycle.self_destruct()

        return payload
